### ISSUE TITLE
TS2307: Cannot find module 'storm-sticky'

### ISSUE THREAD

**Issue by Harti** [mjbp/storm-sticky#3]
First of all, thanks for making this lib! I'm having trouble importing the module using TypeScript though.

I installed storm-sticky as a dependency and confirmed that it is in the node_modules folder. 
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/2056108/43342932-b153e280-91e4-11e8-8994-84e55be9ae56.png">

I've tried various combinations of imports, trying dist files, importing the script as a standalone (but then the variable `Sticky` would not be found on the window object), and so on. 
I have no clue what work is involved in packaging such libraries for npm - maybe there's an export flag to guarantee TypeScript compatibility?
The folder in and by itself is recognized, i.e. paths are autocompleted and all. For the actual import to work, there must be something missing right now as it's not being recognized as a module. Is there something like "rebuilding a classpath" for node modules?

**Comment by mjbp** [comment]
Hi @Harti , thanks for bringing this to our attention and sorry for the slow response.

It was a bug - I've just patched and re-published the module with the fix @v1.3.2.

In the package.json file the 'main' field identifies the file that's the primary entry point to the module. It was pointing to a file from an older build that doesn't exist any more.

The standalone version is set up to support either commonjs-style requires, or a script tag-based loading exposing a global StormSticky, These are the ways we've been using it on recent projects and hadn't encountered the issue since it's introduction, so thanks again for raising it.
